name: Windows Binary Package

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build-win-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Set up Python 3.9 amd64
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install dependencies
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          python -m venv venv64
          venv64\Scripts\python -m pip install --upgrade pip wheel setuptools pyinstaller
          venv64\Scripts\python -m pip install .
      - name: Make package
        shell: cmd
        run: |
          venv64\Scripts\pyinstaller -n rmview --collect-all rmview --icon=assets\rmview.ico -F ./src/rmview/__main__.py
          md public
          move dist\rmview.exe public\rmview.exe
      - name: Package into zip
        uses: papeloto/action-zip@v1
        with:
          files: public/
          recursive: false
          dest: rmview_win_amd64_${{ steps.get_version.outputs.VERSION }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          #body_path: doc/CHANGELOG-${{ steps.get_version.outputs.VERSION }}.txt
          files: rmview_win_amd64_${{ steps.get_version.outputs.VERSION }}.zip
